---
- name: "Prepare Cluster Vault"
  hosts: all
  gather_facts: true
  become: true
  roles:
    - common

- name: "Install Vault Transit"
  hosts: transit
  gather_facts: true
  become: true
  roles:
    - transit

- name: "Install Vault 1"
  hosts: vault_1
  gather_facts: true
  become: true
  roles:
    - vault_1

- name: "Install Vault 2"
  hosts: vault_2
  gather_facts: true
  become: true
  roles:
    - vault_2

- name: "Install Vault 3"
  hosts: vault_3
  gather_facts: true
  become: true
  roles:
    - vault_3