# -*- mode: ruby -*-
# vi: set ft=ruby :
#https://dev.to/kennibravo/vagrant-for-beginners-getting-started-with-examples-jlm
#https://gist.github.com/hodak/4b5256ac0d3f3b11c51ee5309e60367d
#https://developer.hashicorp.com/vagrant/docs/networking/forwarded_ports

NUM_NODES = 3
NUM_CONTROLLER_NODE = 1
IP_NTW = "192.168.56."
CONTROLLER_IP_START = 2
NODE_IP_START = 3

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    id_rsa_pub = File.read("#{Dir.home}/.ssh/id_rsa.pub")

    (1..NUM_NODES).each do |i|
        config.vm.define "vault0#{i}" do |node|
        config.vm.provision "copy ssh public key", type: "shell",
        inline: "echo \"#{id_rsa_pub}\" >> /home/vagrant/.ssh/authorized_keys"
        config.vm.network "forwarded_port", guest: 8200, host: 8200,
        auto_correct: true
        config.vm.network "forwarded_port", guest: 8201, host: 8201,
        auto_correct: true
            node.vm.provider "virtualbox" do |vb|
                vb.name = "vault0#{i}"
                vb.memory = 2048
                vb.cpus = 2
            end

            node.vm.hostname = "vault0#{i}"
            node.vm.network "private_network", ip: IP_NTW + "#{NODE_IP_START + i}"
            node.vm.network "forwarded_port", guest: 22, host: "#{2720 + i}"

        end
    end

    i = 0

    (1..NUM_CONTROLLER_NODE).each do [i] 
        config.vm.define "transit" do |node|
        config.vm.provision "copy ssh public key", type: "shell",
        inline: "echo \"#{id_rsa_pub}\" >> /home/vagrant/.ssh/authorized_keys"
        config.vm.network "forwarded_port", guest: 8200, host: 8200,
        auto_correct: true
        config.vm.network "forwarded_port", guest: 8201, host: 8201,
        auto_correct: true
            node.vm.provider "virtualbox" do |vb|
                vb.name = "transit"
                vb.memory = 2048
                vb.cpus = 2
            end

            node.vm.hostname = "transit"
            node.vm.network "private_network", ip: IP_NTW + "#{CONTROLLER_IP_START + i}"
            node.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"
        end
    end
end