- name: Create initial snapshot
  ansible.builtin.shell: |
    cd "{{ vault_snap }}"
    vault operator raft snapshot save initial.snapshot
    ls -lha
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"
  register: list_snap

- name: Print snap file
  ansible.builtin.debug:
    msg: "{{list_snap.stdout_lines}}"
